apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-hello-app
    spec:
      containers:
        - name: my-hello-app
          image: docker.io/dhodvogner/my-hello-app:latest
          ports:
            - containerPort: 80
